# Template Service Module Configuration

module:
  name: template-service
  version: 1.0.0

server:
  port: ${PORT:-3037}
  host: ${HOST:-0.0.0.0}

cosmos_db:
  endpoint: ${COSMOS_DB_ENDPOINT}
  key: ${COSMOS_DB_KEY}
  database_id: ${COSMOS_DB_DATABASE_ID:-castiel}
  containers:
    templates: template_templates
    versions: template_versions
    context_templates: template_context_templates
    email_templates: template_email_templates

services:
  ai_service:
    url: ${AI_SERVICE_URL:-http://localhost:3006}
  logging:
    url: ${LOGGING_URL:-http://localhost:3014}

rabbitmq:
  url: ${RABBITMQ_URL}
  exchange: coder_events
  queue: template_service

